CREATE TABLE IF NOT EXISTS urls (
  id SERIAL PRIMARY KEY,
  url VARCHAR(255) NOT NULL,
  short_url VARCHAR(255) NOT NULL UNIQUE,
  robots_allowed BOOLEAN DEFAULT TRUE,
  robots_html TEXT DEFAULT NULL
);